server:
  port: ":8765"
mysql:
  db: "bee"
  host: "localhost"
  port: "3306"
  username: "root"
  password: "0987654321"
  maxOpenConns: 10
  maxIdleConns: 10
file:
  thumb: "thumb"
  original: "original"
  path: "/usr/local/var/www/file"
  host: "http://localhost:9006"  
