server:
  port: ":8765"
mysql:
  db: "bee"
  host: "localhost"
  port: "3306"
  username: "root"
  password: "LEE_1826@CSC"
  maxOpenConns: 10
  maxIdleConns: 10
file:
  thumb: "thumb"
  path: "D:/www/file"
  original: "original"
  host: "http://localhost:9001"
