server:
  port: ":8765"
mysql:
  db: "bee"
  host: "localhost"
  port: "3306"
  username: "root"
  password: "LEE_1826@CSC"
  maxOpenConns: 10
  maxIdleConns: 10
file:
  path: "/usr/local/var/www/file/image"
  thumb: "/usr/local/var/www/file/image/thumb"
  host: "http://localhost:9006/image/"
